on:
  pull_request:
  push:
    branches:
      - mainss
jobs:
  build-node:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    container: node:16
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show node and npm versions
        run: |
          node -v
          npm -v
      - name: Install dependencies
        run: |
          npm install
          npm install trufflehog
      - name: Test
        run: |
          npx mocha test/app.test.js
          pwd

  SonarCloud:
    needs: build-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  
#   Trufflehog:
#       needs: build-node
#       runs-on: ubuntu-latest
#       steps:        
#        - uses: actions/checkout@master
#        - name:  trufflehog-actions-scan
#          uses: edplato/trufflehog-actions-scan@v0.9l-beta
         
#   Gitleaks_scan:
#     needs: build-node
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#       - uses: gitleaks/gitleaks-action@v2
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
