on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
    -uses: actions/checkout@v3
      
    -name: Install Dependencies
     run: |
      npm install
      node app.js
        
     -name: Test
      run: npx mocha test/app.test.js
