on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show node and npm versions
        run: |
          node -v
          npm -v
      - name: Install dependencies
        run: |
          npm install
          npm install trufflehog
      - name: Test
        run: npx mocha test/app.test.js
      - name: Security Scan - TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.42.0

        
