on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
      - run: |
          node --version
          npm --version
          npm install
          node app.js
