on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: LS before checkout
        run: |
          ls
        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: LS after checkout
        run: | 
          ls

  build-2:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
    
