name: CI_Workflow

on:
  workflow_call:
jobs:
  CI_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show node and npm versions
        run: |
          node -v
          npm -v
      - name: Install dependencies
        run: |
          npm install
      - name: Test
        run: |
          npx mocha test/app.test.js
          pwd

