name: Repo_Dispatch_Demo

on:
  push: 
#workflow_dispatch:

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Repo-Dispatch
      uses: peter-evans/repository-dispatch@v2.1.1
      with:
        REPO_ACCESS_TOKEN: ${{ secrets.REPO_DISPATCH_ACCESS_TOKEN }}
        repository: adysis14/github_package_demo
        event-type: dependency-update
        
#     - name: Trigger repo_dispatch
#       env:
#         REPO_ACCESS_TOKEN: ${{ secrets.REPO_DISPATCH_ACCESS_TOKEN }}
#         REPO: adysis14/github_package_demo # Replace with the target repository in the format "owner-name/repository-name"
#         DISPATCH_EVENT_TYPE: dependency-update # Replace with the event type you want to trigger in the target repository
#       run: |
#         curl -X POST \
#           -H "Authorization: Bearer $REPO_ACCESS_TOKEN" \
#           -H "Accept: application/vnd.github.everest-preview+json" \
#           https://api.github.com/repos/$REPO/dispatches \
#           -d '{"event_type": "$DISPATCH_EVENT_TYPE"}'
